w3c/attribution

- api.bs
Same as #14 but targeting main.
> Security and privacy considerations

- api.bs
a few minor edits in the first half of the document
> minor edits

- api.bs
> Set a default for `lifetimeDays`

- api.bs
> Replace hardcoded week with privacy budget epoch

- .pr-preview.json
> Fix Bikeshed file name in pr-preview config

- api.bs
And rename some variables.
Closes #66.
***
<a href="https://pr-preview.s3.amazonaws.com/w3c/ppa/pull/89.html" title="Last updated on Feb 18, 2025, 10:01 PM UTC (d50daa9)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/ppa/89/764f599...d50daa9.html" title="Last updated on Feb 18, 2025, 10:01 PM UTC (d50daa9)">Diff</a>
> Add an example of API use for the aggregation service

- api.bs
***
<a href="https://pr-preview.s3.amazonaws.com/w3c/ppa/pull/95.html" title="Last updated on Feb 20, 2025, 10:54 PM UTC (16209c6)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/ppa/95/75d1650...16209c6.html" title="Last updated on Feb 20, 2025, 10:54 PM UTC (16209c6)">Diff</a>
> Split API usage and internals into two sections

- api.bs
***
<a href="https://pr-preview.s3.amazonaws.com/w3c/ppa/pull/96.html" title="Last updated on Feb 21, 2025, 3:31 PM UTC (e651716)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/ppa/96/2a76990...e651716.html" title="Last updated on Feb 21, 2025, 3:31 PM UTC (e651716)">Diff</a>
> Move permission policy section to API usage

- api.bs
Part of #63
***
<a href="https://pr-preview.s3.amazonaws.com/apasel422/ppa-api/pull/97.html" title="Last updated on Feb 21, 2025, 4:09 PM UTC (17ee7cc)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/ppa/97/2a76990...apasel422:17ee7cc.html" title="Last updated on Feb 21, 2025, 4:09 PM UTC (17ee7cc)">Diff</a>
> Clarify filter-data handling in common matching logic

- api.bs
Fixes #99
***
<a href="https://pr-preview.s3.amazonaws.com/apasel422/ppa-api/pull/103.html" title="Last updated on Feb 25, 2025, 1:26 PM UTC (d86d937)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/ppa/103/406829d...apasel422:d86d937.html" title="Last updated on Feb 25, 2025, 1:26 PM UTC (d86d937)">Diff</a>
> Replace DOMString with USVString in URL/site-typed fields

- api.bs
***
<a href="https://pr-preview.s3.amazonaws.com/apasel422/ppa-api/pull/110.html" title="Last updated on Feb 27, 2025, 3:36 PM UTC (f7e404a)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/ppa/110/9b8f9ef...apasel422:f7e404a.html" title="Last updated on Feb 27, 2025, 3:36 PM UTC (f7e404a)">Diff</a>
> Fix minor typo

- api.bs
Mostly, this is just adding some explanatory text.
***
<a href="https://pr-preview.s3.amazonaws.com/w3c/ppa/pull/105.html" title="Last updated on Feb 27, 2025, 1:28 AM UTC (63a3eb9)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/ppa/105/a4c65c4...63a3eb9.html" title="Last updated on Feb 27, 2025, 1:28 AM UTC (63a3eb9)">Diff</a>
> A better example of saving an impression

- api.bs
These don't really need to be understood to understand how to use the API.  At least not in the first instance.
***
<a href="https://pr-preview.s3.amazonaws.com/w3c/ppa/pull/104.html" title="Last updated on Feb 27, 2025, 2:55 AM UTC (bf3f44f)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/ppa/104/a4c65c4...bf3f44f.html" title="Last updated on Feb 27, 2025, 2:55 AM UTC (bf3f44f)">Diff</a>
> Move operations to "internals" section

- api.bs
***
<a href="https://pr-preview.s3.amazonaws.com/apasel422/ppa-api/pull/111.html" title="Last updated on Mar 3, 2025, 4:55 PM UTC (cff8e39)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/ppa/111/60a439f...apasel422:cff8e39.html" title="Last updated on Mar 3, 2025, 4:55 PM UTC (cff8e39)">Diff</a>
> Link to enum declarations

- README.md
We didn't do that after the many moves, so we should do that now.
> Update the readme with updated status

- api.bs
***
<a href="https://pr-preview.s3.amazonaws.com/w3c/ppa/pull/118.html" title="Last updated on Mar 27, 2025, 6:16 AM UTC (00e1d2f)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/ppa/118/8c1f6c2...00e1d2f.html" title="Last updated on Mar 27, 2025, 6:16 AM UTC (00e1d2f)">Diff</a>
> Add some context to the Navigator interface section

- api.bs
> Clarify which origin is passed to 'obtain a site'

- examples/examples.md
Adding a space where contributors can put examples for discussion. Resolves action item from https://github.com/w3c/patwg/blob/main/meetings/2025/02-telecons/02-11-minutes.md#action-item-list
> Adding example use cases folder

- api.bs
#132, #46
***
<a href="https://pr-preview.s3.amazonaws.com/apasel422/ppa-api/pull/164.html" title="Last updated on May 16, 2025, 11:46 AM UTC (64c1521)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/ppa/164/b01b4b4...apasel422:64c1521.html" title="Last updated on May 16, 2025, 11:46 AM UTC (64c1521)">Diff</a>
> Permit sets of filter data in HTTP API

- api.bs
This is the name we agreed to.  I'm not convinced that it's ideal, but it is certainly better than what we had.
Closes #24.
***
<a href="https://pr-preview.s3.amazonaws.com/w3c/ppa/pull/159.html" title="Last updated on May 19, 2025, 4:57 AM UTC (87be7ec)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/ppa/159/364a9eb...87be7ec.html" title="Last updated on May 19, 2025, 4:57 AM UTC (87be7ec)">Diff</a>
> filterData -> matchValue

- api.bs
Closes #129.
***
<a href="https://pr-preview.s3.amazonaws.com/w3c/ppa/pull/149.html" title="Last updated on May 20, 2025, 1:32 AM UTC (8a0896b)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/ppa/149/b26b200...8a0896b.html" title="Last updated on May 20, 2025, 1:32 AM UTC (8a0896b)">Diff</a>
> Fingerprinting risk of unconfigured browsers

- .github/workflows/auto-publish.yml
Toolchain update and re-test after api.bs edits
> retry auto-publish

- api.bs
***
<a href="https://pr-preview.s3.amazonaws.com/apasel422/ppa-api/pull/194.html" title="Last updated on Jun 3, 2025, 2:03 PM UTC (636bc6c)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/ppa/194/7b19a6e...apasel422:636bc6c.html" title="Last updated on Jun 3, 2025, 2:03 PM UTC (636bc6c)">Diff</a>
> Replace reference to nonexistent site variable with topLevelSite

- api.bs
Fix post #191
***
<a href="https://pr-preview.s3.amazonaws.com/apasel422/ppa-api/pull/199.html" title="Last updated on Jun 4, 2025, 3:16 PM UTC (ff56ebc)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/ppa/199/1c5289e...apasel422:ff56ebc.html" title="Last updated on Jun 4, 2025, 3:16 PM UTC (ff56ebc)">Diff</a>
> Resolve promise instead of throwing error for too many conversion sites

- .github/workflows/auto-publish.yml
- api.bs
As agreed.
@tjwhalen we have a few open bits in the metadata that we'd need to coordinate here.
Closes #202.
***
<a href="https://pr-preview.s3.amazonaws.com/w3c/ppa/pull/203.html" title="Last updated on Jun 11, 2025, 1:21 PM UTC (d5e5a89)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/ppa/203/23f8eca...d5e5a89.html" title="Last updated on Jun 11, 2025, 1:21 PM UTC (d5e5a89)">Diff</a>
> Rename the API to "Attribution"

- api.bs
https://www.w3.org/Provider/Style/URI !!!
Closes #154.
***
<a href="https://pr-preview.s3.amazonaws.com/w3c/ppa/pull/210.html" title="Last updated on Jun 20, 2025, 12:34 AM UTC (d1fdb12)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/ppa/210/b9a9fd0...d1fdb12.html" title="Last updated on Jun 20, 2025, 12:34 AM UTC (d1fdb12)">Diff</a>
> Fix more broken links

- api.bs
***
<a href="https://pr-preview.s3.amazonaws.com/w3c/ppa/pull/215.html" title="Last updated on Jun 26, 2025, 10:29 PM UTC (66effa9)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/ppa/215/da3cbdc...66effa9.html" title="Last updated on Jun 26, 2025, 10:29 PM UTC (66effa9)">Diff</a>
> Remove the colon

- Makefile
- api.bs
***
<a href="https://pr-preview.s3.amazonaws.com/w3c/ppa/pull/225.html" title="Last updated on Aug 1, 2025, 3:36 AM UTC (8e38ef8)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/ppa/225/260bfe4...8e38ef8.html" title="Last updated on Aug 1, 2025, 3:36 AM UTC (8e38ef8)">Diff</a>
> Fair integer credit assignment

- impl/package-lock.json
- impl/package.json
- impl/src/e2e.test.ts
> Reorganize e2e tests in preparation for JSON format

- .github/workflows/deploy.yml
Bikeshed has been tested up to python 3.11
> Pin python version for Build HTML step

- impl/src/e2e.test.ts
> Demonstrate saving multiple impressions for use in separate queries

- api.bs
***
<a href="https://pr-preview.s3.amazonaws.com/apasel422/ppa-api/pull/249.html" title="Last updated on Aug 14, 2025, 12:38 PM UTC (2144c00)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/attribution/249/2c321cf...apasel422:2144c00.html" title="Last updated on Aug 14, 2025, 12:38 PM UTC (2144c00)">Diff</a>
> Add missing link

- .github/workflows/check.yml
Which might help with build failures
> Change cache key

- impl/e2e-tests/match-values.json
- impl/e2e-tests/no-matching-impression.json
- impl/src/backend.ts
The latter being split off from #278, since it is not strictly related.
> Add e2e tests for matching and fix credit-array truncation
