w3c/attribution

- api.bs
At TPAC, we discussed a few changes to this spec:
1. Using "filterData" instead of enumerating a list of ad identifiers. For now, the proposal was to use the simplest approach of a single integer.
2. Storing information in the impression store about the script which invoked the saveImpression API, which might be a 3rd party script, and might be within an iframe. This could later be used for impression filtering and in the future, as a breakdown key.
3. Providing the maximum conversion value to the device in the saveImpression call as it will be used to deduct appropriate privacy budget loss.
> Post TPAC Update

- api.bs
not having the `()` on the methods was causing bikeshed to fail, causing the github checks to fail.
> fix errors when building bikeshed

- README.md
with the move into the `patcg` org, the URL of the web version needs to be updated.
> Update README.md link to account for org move

- api.bs
This PR deducts budget from all epochs with matching impressions, as per the [cookie monster](https://arxiv.org/pdf/2405.16719) paper.
It also decouples a "common" attribution algorithm from the last-touch one, as all attribution algorithms need to first invoke the common matching logic and do budget deduction in the same way.
Fixes #75
> Align the attribution algorithm with Cookie Monster

- api.bs
["empty"](https://infra.spec.whatwg.org/#list-empty) clears a list, while ["is empty"](https://infra.spec.whatwg.org/#list-is-empty) returns whether the list's size is 0.
> Replace erroneous links to "empty" algorithm with "is empty"

- api.bs
Bikeshed insists on the org being set and won't accept a custom group, despite its documentation saying otherwise.  So, until we need some sort of custom boilerplate, let's not worry about that business.
Closes #82.
> Fix org and group metadata

- api.bs
Fixes #81
***
<a href="https://pr-preview.s3.amazonaws.com/apasel422/ppa-api/pull/86.html" title="Last updated on Feb 10, 2025, 1:47 PM UTC (ad3019c)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/ppa/86/f05176c...apasel422:ad3019c.html" title="Last updated on Feb 10, 2025, 1:47 PM UTC (ad3019c)">Diff</a>
> Reject zero as a value for impression lifetime

- api.bs
WebIDL does not define a `Throws` extended attribute for now. The possibility to define it is tracked in https://github.com/whatwg/webidl/issues/603
***
<a href="https://pr-preview.s3.amazonaws.com/tidoust/ppa/pull/91.html" title="Last updated on Feb 17, 2025, 1:42 AM UTC (fa2e9f4)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/ppa/91/764f599...tidoust:fa2e9f4.html" title="Last updated on Feb 17, 2025, 1:42 AM UTC (fa2e9f4)">Diff</a>
> Drop non-standard IDL `Throws` extended attribute

- api.bs
Fixes #85
***
<a href="https://pr-preview.s3.amazonaws.com/apasel422/ppa-api/pull/87.html" title="Last updated on Feb 10, 2025, 1:51 PM UTC (2ff420f)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/ppa/87/f05176c...apasel422:2ff420f.html" title="Last updated on Feb 10, 2025, 1:51 PM UTC (2ff420f)">Diff</a>
> Wrap measureConversion return type in a dictionary for future extensions

- api.bs
And improve our linking of those concepts throughput.
This does the core "impression/conversion/intermediary site" and "epoch" definitions.
***
<a href="https://pr-preview.s3.amazonaws.com/w3c/ppa/pull/90.html" title="Last updated on Feb 20, 2025, 4:16 AM UTC (7d461e9)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/ppa/90/764f599...7d461e9.html" title="Last updated on Feb 20, 2025, 4:16 AM UTC (7d461e9)">Diff</a>
> Work on adding definitions for core concepts

- api.bs
This PR adds basic privacy budgeting, without getting into the safety limit budgeting (which I still need to think about).
cc #77 .  This PR still uses floating point budgeting which is the simplest approach until we resolve that issue.
***
<a href="https://pr-preview.s3.amazonaws.com/csharrison/ppa-api/pull/79.html" title="Last updated on Feb 20, 2025, 9:30 PM UTC (ed2279b)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/ppa/79/d632416...csharrison:ed2279b.html" title="Last updated on Feb 20, 2025, 9:30 PM UTC (ed2279b)">Diff</a>
> Spec basic privacy budgeting

- api.bs
CC #63
***
<a href="https://pr-preview.s3.amazonaws.com/apasel422/ppa-api/pull/74.html" title="Last updated on Feb 20, 2025, 9:30 PM UTC (bf3ea8f)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/ppa/74/d632416...apasel422:bf3ea8f.html" title="Last updated on Feb 20, 2025, 9:30 PM UTC (bf3ea8f)">Diff</a>
> Define type for stored impressions and use it in algorithms

- api.bs
It is already optional in PrivateAttributionConversionOptions, and described as optional in the detailed description of PrivateAttributionImpressionOptions.
> Make filterData optional in PrivateAttributionImpressionOptions

- api.bs
This text was removed when replacing the ad identifier with filter data. Since I think the consideration remains more or less the same, this change restores the text, modifying it to refer to filter data.
***
<a href="https://pr-preview.s3.amazonaws.com/w3c/ppa/pull/71.html" title="Last updated on Feb 20, 2025, 9:52 PM UTC (688a4a3)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/ppa/71/0609f54...688a4a3.html" title="Last updated on Feb 20, 2025, 9:52 PM UTC (688a4a3)">Diff</a>
> Restore a subsection of privacy considerations

- api.bs
According to Tab:
> The only purpose of Group is to opt into group-specific boilerplate, so there's no reason to list a Group value that's not present in the doctypes file.
-- https://github.com/speced/bikeshed/issues/3022#issuecomment-2672864705
***
<a href="https://pr-preview.s3.amazonaws.com/w3c/ppa/pull/94.html" title="Last updated on Feb 20, 2025, 10:51 PM UTC (3f6206b)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/ppa/94/75d1650...3f6206b.html" title="Last updated on Feb 20, 2025, 10:51 PM UTC (3f6206b)">Diff</a>
> Remove not-Group from metadata

- api.bs
Fixes #98
***
<a href="https://pr-preview.s3.amazonaws.com/apasel422/ppa-api/pull/100.html" title="Last updated on Feb 24, 2025, 1:15 PM UTC (1e3050d)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/ppa/100/09e9a68...apasel422:1e3050d.html" title="Last updated on Feb 24, 2025, 1:15 PM UTC (1e3050d)">Diff</a>
> Fix broken "obtain a site" links

- api.bs
1. Reject `lookbackDays == 0`.
2. Treat omitted `lookbackDays` as an implementation-defined maximum.
3. Use a consistent notion of `now`.
Fixes #63
***
<a href="https://pr-preview.s3.amazonaws.com/apasel422/ppa-api/pull/101.html" title="Last updated on Feb 25, 2025, 1:24 PM UTC (2b66dc5)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/ppa/101/09e9a68...apasel422:2b66dc5.html" title="Last updated on Feb 25, 2025, 1:24 PM UTC (2b66dc5)">Diff</a>
> Address TODOs around parameter validation and defaulting

- api.bs
In doing so, I realized that the ordering of the process and the ordering of the attributes on the dictionary didn't really make sense from a narrative perspective, so I reordered them.  It's a simple move.
***
<a href="https://pr-preview.s3.amazonaws.com/w3c/ppa/pull/108.html" title="Last updated on Feb 27, 2025, 1:26 AM UTC (52311b2)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/ppa/108/60864cb...52311b2.html" title="Last updated on Feb 27, 2025, 1:26 AM UTC (52311b2)">Diff</a>
> Expand on the measureConversion example

- api.bs
The [`PrivateAttributionAggregationServices` interface](https://w3c.github.io/ppa/#privateattributionaggregationservices) is [`setlike`](https://webidl.spec.whatwg.org/#js-setlike), so in order to call `some` we must first call `values`.
***
<a href="https://pr-preview.s3.amazonaws.com/apasel422/ppa-api/pull/112.html" title="Last updated on Mar 3, 2025, 5:14 PM UTC (f6ded4d)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/ppa/112/60a439f...apasel422:f6ded4d.html" title="Last updated on Mar 3, 2025, 5:14 PM UTC (f6ded4d)">Diff</a>
> Fix erroneous usage of `some` method in example code

- api.bs
***
<a href="https://pr-preview.s3.amazonaws.com/apasel422/ppa-api/pull/115.html" title="Last updated on Mar 12, 2025, 4:40 PM UTC (637ca14)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/ppa/115/3dfabee...apasel422:637ca14.html" title="Last updated on Mar 12, 2025, 4:40 PM UTC (637ca14)">Diff</a>
> Clean up specification links, terminology, and TODOs

- api.bs
Fixes #116
***
<a href="https://pr-preview.s3.amazonaws.com/apasel422/ppa-api/pull/117.html" title="Last updated on Mar 24, 2025, 1:57 PM UTC (e174c5d)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/ppa/117/1447c76...apasel422:e174c5d.html" title="Last updated on Mar 24, 2025, 1:57 PM UTC (e174c5d)">Diff</a>
> Explain difference in defaulting of filterData fields

- api.bs
This makes a batch of changes to the last-touch logic.  The main functional change is that it adds validation for `value` and `maxValue`.
***
<a href="https://pr-preview.s3.amazonaws.com/w3c/ppa/pull/120.html" title="Last updated on Mar 27, 2025, 6:53 AM UTC (23205a0)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/ppa/120/8c1f6c2...23205a0.html" title="Last updated on Mar 27, 2025, 6:53 AM UTC (23205a0)">Diff</a>
> Last touch validation

- api.bs
The `<dl class="switch">` element did not fully wrap the inner clause, preventing Bikeshed from applying the right styles to the clause.
***
<a href="https://pr-preview.s3.amazonaws.com/tidoust/ppa/pull/124.html" title="Last updated on Mar 31, 2025, 5:56 PM UTC (eab037d)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/ppa/124/6832973...tidoust:eab037d.html" title="Last updated on Mar 31, 2025, 5:56 PM UTC (eab037d)">Diff</a>
> Editorial: fix "switch" clause wrapping

- api.bs
We're trying to keep this accessible, but these definitions jumped right into the technical deep end immediately.  Soften the landing a little.
***
<a href="https://pr-preview.s3.amazonaws.com/w3c/ppa/pull/119.html" title="Last updated on Apr 1, 2025, 4:51 AM UTC (ef076a5)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/ppa/119/8c1f6c2...ef076a5.html" title="Last updated on Apr 1, 2025, 4:51 AM UTC (ef076a5)">Diff</a>
> Improve site definitions

- api.bs
This turned into a bit of an epic, but it implements the changes we
discussed about site-state clearing, epoch start time, and all the
associated logic.
This defines when epochs start (randomly, as agreed).
This defines a store for that per-site state and integrates a new
algorithm for getting the current epoch.
It defines a persistent clear-state time variable that tracks when any
site state was cleared.  This value blocks out use of the API globally
for a period.
I've added notes about partitioning the state-cleared variable, but not
specified anything for that.  That seems like a reasonable balance to
me; as the text says, this is the most private option.
Closes #17.
***
<a href="https://pr-preview.s3.amazonaws.com/w3c/ppa/pull/121.html" title="Last updated on Apr 1, 2025, 11:20 PM UTC …
> Define epoch

- api.bs
The algorithm to create an empty histogram requires an integer size.
***
<a href="https://pr-preview.s3.amazonaws.com/apasel422/ppa-api/pull/131.html" title="Last updated on Apr 3, 2025, 9:57 PM UTC (7422854)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/ppa/131/f63ab46...apasel422:7422854.html" title="Last updated on Apr 3, 2025, 9:57 PM UTC (7422854)">Diff</a>
> Provide histogram size when API is disabled

- api.bs
And an analysis of why our choice is acceptable.
I didn't have to rely on the fact that most clock adjustments are small,
except somewhat indirectly.  Instead, it mentions that large forward
adjustments that might cause a change of epoch each have an
instantaneous effect on privacy by refreshing the budget.
I had to add some additional context about privacy goals to this one,
so that the discussion on recognition made sense.
Closes #123.
***
<a href="https://pr-preview.s3.amazonaws.com/w3c/ppa/pull/128.html" title="Last updated on Apr 3, 2025, 9:58 PM UTC (322538a)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/ppa/128/f63ab46...322538a.html" title="Last updated on Apr 3, 2025, 9:58 PM UTC (322538a)">Diff</a>
> Add text about the choice of clock 

- api.bs
***
<a href="https://pr-preview.s3.amazonaws.com/apasel422/ppa-api/pull/133.html" title="Last updated on Apr 4, 2025, 1:20 PM UTC (7227473)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/ppa/133/c66a938...apasel422:7227473.html" title="Last updated on Apr 4, 2025, 1:20 PM UTC (7227473)">Diff</a>
> Fix erroneous references to impression-vs-conversion filterData

- api.bs
Fixes #134, #137, #138
***
<a href="https://pr-preview.s3.amazonaws.com/apasel422/ppa-api/pull/139.html" title="Last updated on Apr 9, 2025, 5:27 PM UTC (fb89d1e)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/ppa/139/eba7f55...apasel422:fb89d1e.html" title="Last updated on Apr 9, 2025, 5:27 PM UTC (fb89d1e)">Diff</a>
> Use consistent set semantics for impression/conversion sites

- README.md
- api.bs
This is built on https://github.com/w3c/ppa/pull/104.
This contributes to https://github.com/w3c/ppa/issues/102 by laying some of the ground work regarding
sites.  It should now be possible to "parse a site" when preparing to
invoke the matching logic.  That comes next.
***
<a href="https://pr-preview.s3.amazonaws.com/w3c/ppa/pull/106.html" title="Last updated on Apr 24, 2025, 6:18 AM UTC (7f62ed2)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/ppa/106/eba7f55...7f62ed2.html" title="Last updated on Apr 24, 2025, 6:18 AM UTC (7f62ed2)">Diff</a>
> Add procedures for parsing site names from strings 

- api.bs
Not the impression site; that was in error.
Closes #141.
> Epoch start is tied to conversion site

- api.bs
Yes, this is not a general solution, but it works for the diagrams we have and it is less jarring than the white background.
> Use haxx to get dark mode for figures

- api.bs
***
<a href="https://pr-preview.s3.amazonaws.com/w3c/ppa/pull/56.html" title="Last updated on Apr 10, 2025, 8:37 AM UTC (dd2b274)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/ppa/56/3dfabee...dd2b274.html" title="Last updated on Apr 10, 2025, 8:37 AM UTC (dd2b274)">Diff</a>
> Initial detail of HTTP API

- api.bs
When the set is empty, any value matches.
Fixes #132.
> Allow conversions to match a set of filter data values

- .github/workflows/check.yml
This caches pip depedencies so that builds run a little faster.
They are already pretty quick, but this might be faster yet.
> Cache python dependencies for CI

- api.bs
Looking at @csharrison here for a review.
I threw in a fix for #125 with this as a bonus.
***
<a href="https://pr-preview.s3.amazonaws.com/w3c/ppa/pull/126.html" title="Last updated on Apr 24, 2025, 11:10 PM UTC (99e6f04)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/ppa/126/f63ab46...99e6f04.html" title="Last updated on Apr 24, 2025, 11:10 PM UTC (99e6f04)">Diff</a>
> Some followup changes regarding epochs

- api.bs
This monkey-patches the Clear-Site-Data spec, which monkey-patches fetch.  🙊
Closes #125.
***
<a href="https://pr-preview.s3.amazonaws.com/w3c/ppa/pull/160.html" title="Last updated on May 19, 2025, 5:02 AM UTC (02cbd8f)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/ppa/160/b01b4b4...02cbd8f.html" title="Last updated on May 19, 2025, 5:02 AM UTC (02cbd8f)">Diff</a>
> Clear-Site-Data integration

- api.bs
This converts the underlying type from a CSS float (yes, we were citing CSS, not a numeric type) to a 32-bit integer.  I figure that an epsilon of 4000 is unnecessary, so this seemed like a nice way to manage it.
The algorithm is slightly different and I've tweaked some of the references to it.  Most of that is just referencing and cleanup.
Closes #77.
***
<a href="https://pr-preview.s3.amazonaws.com/w3c/ppa/pull/161.html" title="Last updated on May 20, 2025, 1:35 AM UTC (8dae34b)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/ppa/161/b01b4b4...8dae34b.html" title="Last updated on May 20, 2025, 1:35 AM UTC (8dae34b)">Diff</a>
> Deal with privacy budget rounding

- api.bs
This explains how the PrioL1BoundSum proofs are constructed from the maxValue that is provided.
Some cleanup of the surrounding text was included so that the DAP section has some structure.
Closes #107.
***
<a href="https://pr-preview.s3.amazonaws.com/w3c/ppa/pull/163.html" title="Last updated on May 19, 2025, 5:00 AM UTC (754a393)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/ppa/163/b01b4b4...754a393.html" title="Last updated on May 19, 2025, 5:00 AM UTC (754a393)">Diff</a>
> Deal with maxValue and DAP proofs

- api.bs
To match the JavaScript API, which currently defaults to the empty set.
> Make conversion-sites optional in HTTP API

- api.bs
https://webidl.spec.whatwg.org/#method-steps
This also addresses the confusing situation of there being multiple dfns associated with saveImpression and measureConversion.
***
<a href="https://pr-preview.s3.amazonaws.com/apasel422/ppa-api/pull/169.html" title="Last updated on May 21, 2025, 5:40 PM UTC (12190eb)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/ppa/169/8262319...apasel422:12190eb.html" title="Last updated on May 21, 2025, 5:40 PM UTC (12190eb)">Diff</a>
> Define IDL methods using "method steps" approach

- api.bs
With this change, it is possible to click on a variable and see all its uses highlighted within the algorithm scope, and to be warned about missing definitions / unused variables.
https://speced.github.io/bikeshed/#var-and-algorithms
> Wrap algorithms in <div algorithm> to generate variable references

- api.bs
Metadata and diagram style (unnested CSS) updated to work with autopublish scripts
***
<a href="https://pr-preview.s3.amazonaws.com/tjwhalen/ppa/pull/173.html" title="Last updated on May 22, 2025, 5:12 PM UTC (6f10eba)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/ppa/173/3f53acb...tjwhalen:6f10eba.html" title="Last updated on May 22, 2025, 5:12 PM UTC (6f10eba)">Diff</a>
> Update api.bs - preamble for autopublishing

- api.bs
Based on the example in https://webidl.spec.whatwg.org/#promise-example-validatedDelay.
Fixes #170
***
<a href="https://pr-preview.s3.amazonaws.com/apasel422/ppa-api/pull/171.html" title="Last updated on May 22, 2025, 1:38 PM UTC (4dc7e43)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/ppa/171/3f53acb...apasel422:4dc7e43.html" title="Last updated on May 22, 2025, 1:38 PM UTC (4dc7e43)">Diff</a>
> Return a promise from the measureConversion method steps

- api.bs
Per the note at https://webidl.spec.whatwg.org/#idl-DOMException-error-names.
***
<a href="https://pr-preview.s3.amazonaws.com/apasel422/ppa-api/pull/177.html" title="Last updated on May 27, 2025, 1:26 PM UTC (86ed818)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/ppa/177/1ab0fc2...apasel422:86ed818.html" title="Last updated on May 27, 2025, 1:26 PM UTC (86ed818)">Diff</a>
> Use SyntaxError DOMException rather than JS SyntaxError

- api.bs
Per the WebIDL definition, the JS API defaults to 30 days, rather than an implementation-defined value.
***
<a href="https://pr-preview.s3.amazonaws.com/apasel422/ppa-api/pull/182.html" title="Last updated on May 28, 2025, 12:57 PM UTC (9d815ee)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/ppa/182/82c2aed...apasel422:9d815ee.html" title="Last updated on May 28, 2025, 12:57 PM UTC (9d815ee)">Diff</a>
> Default impression lifetime consistently in JS and HTTP APIs

- api.bs
***
<a href="https://pr-preview.s3.amazonaws.com/apasel422/ppa-api/pull/184.html" title="Last updated on May 28, 2025, 2:55 PM UTC (7e30fbd)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/ppa/184/82c2aed...apasel422:7e30fbd.html" title="Last updated on May 28, 2025, 2:55 PM UTC (7e30fbd)">Diff</a>
> Clarify options field accesses in measureConversion method

- api.bs
***
<a href="https://pr-preview.s3.amazonaws.com/apasel422/ppa-api/pull/187.html" title="Last updated on May 30, 2025, 11:58 AM UTC (2807a19)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/ppa/187/7b19a6e...apasel422:2807a19.html" title="Last updated on May 30, 2025, 11:58 AM UTC (2807a19)">Diff</a>
> Specify parsing of Save-Impression HTTP header

- api.bs
This doesn't look like a lot, but there's a whole bunch here.
1. There is a discussion of the rule of intermediaries in the API.  This is pretty brief for now, but we can expand it over time.
2. There is a longer discussion about what it means to construct a histogram. There's a new concept here that is introduced, of histogram definition.  This allows me to explain that the semantics of each of the histogram indices used by impressions that are selected by the same `measureConversion()` call need to be consistent.  This section describes the set of tools that the API provides for ensuring that this is possible.
3. Those tools are then defined. The various `intermediarySites` options are renamed.  I've named these `impressionCallers` (on the conversion site) and `conversionCallers` (on …
> Define intermediary interactions with the API

- api.bs
I considered doing this in the way that the issue suggested, but when I got down to it, that would require the definition of a new method to get epoch start and end times.  This does it based on epoch indices.
In short, this iterates all impressions in the store, gets the epoch index that corresponds to the timestamp, and skips any that are not equal to the epoch we're looking at.
I've tweaked the short circuit on lookback to also use epoch index.  It checks whether the epoch index for now - lookback is less than the current epoch.
In practice, this would be horribly inefficient. You would definitely not want to implement things this way.  The upside is that this is fairly straightforward to specify and understand.
Closes #207.
***
<a …
> Define epoch matching

- api.bs
This does a more than thorough definition of what it takes to encrypt a report for DAP/MPC.  This is probably a little TOO detailed, in that the DAP draft specifies most of this.  However, I found it helpful to go to this level of detail because the draft doesn't pin down certain key parameters, like the choice of field and time resolution.
This updates the DAP definition to the latest draft and references the latest DAP report extensions (updated today also).
***
<a href="https://pr-preview.s3.amazonaws.com/w3c/ppa/pull/217.html" title="Last updated on Jul 10, 2025, 7:21 AM UTC (c68932f)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/ppa/217/d18a166...c68932f.html" title="Last updated on Jul 10, 2025, 7:21 AM UTC (c68932f)">Diff</a>
> Encryption for DAP

- api.bs
This PR replaces the last-touch attribution model with a priority-based last-N touch model. The caller can optionally supply a list of `credit` of size N, which will be allocated across the last N matching impressions. Impressions are sorted first by a new `priority` field, then by timestamp.
***
<a href="https://pr-preview.s3.amazonaws.com/w3c/ppa/pull/218.html" title="Last updated on Jul 14, 2025, 5:29 PM UTC (42d07f2)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/ppa/218/d18a166...42d07f2.html" title="Last updated on Jul 14, 2025, 5:29 PM UTC (42d07f2)">Diff</a>
> Spec n-last-touch attribution

- api.bs
For ease of reference.
***
<a href="https://pr-preview.s3.amazonaws.com/apasel422/ppa-api/pull/229.html" title="Last updated on Aug 1, 2025, 12:00 PM UTC (5982dd9)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/ppa/229/260bfe4...apasel422:5982dd9.html" title="Last updated on Aug 1, 2025, 12:00 PM UTC (5982dd9)">Diff</a>
> Introduce constant for max epsilon

- impl/src/backend.ts
The WebIDL definition guarantees this, but JavaScript and TypeScript do not.
> Verify that priority is an integer in simulator

- impl/package.json
For compatibility with versions of node that don't operate on directories themselves.
> Run tests on specific files, rather than directory

- api.bs
- impl/src/backend.ts
Fixes #232
***
<a href="https://pr-preview.s3.amazonaws.com/apasel422/ppa-api/pull/260.html" title="Last updated on Aug 22, 2025, 12:26 PM UTC (48c86c8)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/attribution/260/85e2869...apasel422:48c86c8.html" title="Last updated on Aug 22, 2025, 12:26 PM UTC (48c86c8)">Diff</a>
> Remove lookback-based early return from common matching logic

- api.bs
- impl/src/backend.ts
Fixes #233, #258
***
<a href="https://pr-preview.s3.amazonaws.com/apasel422/ppa-api/pull/259.html" title="Last updated on Aug 22, 2025, 12:18 PM UTC (a6ceb60)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/attribution/259/85e2869...apasel422:a6ceb60.html" title="Last updated on Aug 22, 2025, 12:18 PM UTC (a6ceb60)">Diff</a>
> Clarify impression-caller matching

- api.bs
This explains how at least a few of the easier implementation-defined values can be selected.  Or at least, explains the relationship between them.
It was enough text to justify having a section.  I didn't mark this as informative, though it is and it could be marked thus; I just generally hate the idea that you might mark something informative and then it no longer matters.  That's not how these things work.
There are more and we can continue to expand this section.  I added a TBD for epsilon, which is obviously very, very hard to decide on.
***
<a href="https://pr-preview.s3.amazonaws.com/w3c/attribution/pull/257.html" title="Last updated on Aug 22, 2025, 7:53 AM UTC (069423c)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/attribution/257/4444705...069423c.html" …
> How far back

- api.bs
- impl/src/backend.ts
The whole business with halving and whatnot seemed overly complicated. This is simpler.  I know that this is probably abusing the definition of "sensitivity" and I could be convinced to care about a better name, but it is far easier to read this, I think.
***
<a href="https://pr-preview.s3.amazonaws.com/w3c/attribution/pull/264.html" title="Last updated on Sep 4, 2025, 10:47 PM UTC (d2bc089)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/attribution/264/934b12a...d2bc089.html" title="Last updated on Sep 4, 2025, 10:47 PM UTC (d2bc089)">Diff</a>
> Refactor privacy budget deduction
